remote_theme: qeacourse/minimal-mistakes@copybutton
logo: "images/navisharelogo.jpg"
title: "NaviShare: Pursuing Unfettered Mobility for Folks Who Are Blind"
repository: navishare/navishare.github.io
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: true
